[book]
authors = ["hinto-janai"]
language = "en"
multilingual = false
src = "src"
title = "Cuprate User Book - v0.0.7"
git-repository-url = "https://github.com/Cuprate/cuprate/books/user"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
no-section-label = true

[preprocessor.gen_config]
command = "bash ./books/user/gen_config.sh"
