[package]
name        = "cuprate-rcu-ring"
version     = "0.0.1"
edition     = "2021"
description = "A read-copy-update type that is backed by raw bytes"
license     = "MIT"
authors     = ["Boog900"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/storage/linear-tape/rcu-ring"
keywords    = ["cuprate", "database", "rcu"]

[target.'cfg(any(target_os = "linux", target_os = "android", target_os = "freebsd"))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.0", features = ["Win32_System_Threading", "Win32_Foundation", "Win32_System_WindowsProgramming"] }