[package]
name        = "monero-rpc-server"
version     = "0.0.0"
edition     = "2021"
description = "Monero RPC types"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/rpc/monero-rpc-types"
keywords    = ["monero", "rpc", "types"]

[features]

[dependencies]

[dev-dependencies]
