[package]
name        = "monero-rpc-types"
version     = "0.0.0"
edition     = "2021"
description = "Monero RPC types"
license     = "MIT"
authors     = ["hinto-janai"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/rpc/monero-rpc-types"
keywords    = ["monero", "rpc", "types"]

[features]
default = []

[dependencies]
monero-serai = { workspace = true }
paste        = { workspace = true }
serde        = { workspace = true }
strum        = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
