[package]
name = "cuprate-sync-states"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuprate-common = {path = "../../common"}
cuprate-peer = {path = "../peer"}
cuprate-protocol = {path = "../protocol"}
monero = {git="https://github.com/Boog900/monero-rs.git", branch="db", features=["database"]}
monero-wire = {path= "../../net/monero-wire"}
futures = "0.3.26"
tower = {version = "0.4.13", features = ["util"]}
thiserror = "1.0.39"

