[package]
name = "monero-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Boog900"]

[features]
default = ["borsh"]
borsh = ["dep:borsh", "monero-pruning/borsh"]

[dependencies]
cuprate-helper = { path = "../../helper" }
monero-wire = { path = "../../net/monero-wire", features = ["tracing"] }
monero-pruning = { path = "../../pruning" }

tokio = { workspace = true, features = ["net", "sync", "macros", "time", "rt"]}
tokio-util = { workspace = true, features = ["codec"] }
tokio-stream = { workspace = true, features = ["sync"]}
futures = { workspace = true, features = ["std"] }
async-trait = { workspace = true }
tower = { workspace = true, features = ["util", "tracing"] }

thiserror = { workspace = true }
tracing = { workspace = true, features = ["std", "attributes"] }

borsh = { workspace = true, features = ["derive", "std"], optional = true }

[dev-dependencies]
cuprate-test-utils = {path = "../../test-utils"}

hex = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "rt", "macros"]}
tracing-subscriber = { workspace = true }
