[package]
name = "monero-peer"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
monero-wire = {path= "../../net/monero-wire"}
cuprate-common = {path = "../../common"}

tokio = {version= "1.34.0", default-features = false, features = ["net"]}
tokio-util = { version = "0.7.10", default-features = false, features = ["codec"] }
futures = "0.3.29"
async-trait = "0.1.74"

tower = { version= "0.4.13", features = ["util"] }
thiserror = "1.0.50"

tracing = "0.1.40"

[dev-dependencies]
hex = "0.4.3"
tokio = {version= "1.34.0", default-features = false, features = ["net", "rt-multi-thread", "rt", "macros"]}
tracing-subscriber = "0.3"
