[package]
name        = "cuprate-txpool"
version     = "0.0.0"
edition     = "2021"
description = "Cuprate's transaction pool database"
license     = "MIT"
authors     = ["Boog900"]
repository  = "https://github.com/Cuprate/cuprate/tree/main/storage/txpool"
keywords    = ["cuprate", "txpool", "transaction", "pool", "database"]

[features]
default     = ["heed"]
# default   = ["redb", "service"]
# default   = ["redb-memory", "service"]
heed        = ["cuprate-database/heed"]
redb        = ["cuprate-database/redb"]
redb-memory = ["cuprate-database/redb-memory"]
serde       = ["dep:serde", "cuprate-database/serde", "cuprate-database-service/serde", "cuprate-helper/serde"]

[dependencies]
cuprate-database         = { workspace = true, features = ["heed"] }
cuprate-database-service = { workspace = true }
cuprate-types            = { workspace = true, features = ["rpc"] }
cuprate-helper           = { workspace = true, default-features = false, features = ["constants", "time"] }

monero-oxide             = { workspace = true, features = ["std"] }
bytemuck                 = { workspace = true, features = ["must_cast", "derive", "min_const_generics", "extern_crate_alloc"] }
bitflags                 = { workspace = true, features = ["std", "serde", "bytemuck"] }
thiserror                = { workspace = true }
hex                      = { workspace = true, features = ["std"] }
blake3                   = { workspace = true, features = ["std"] }
tracing                  = { workspace = true }

tower                    = { workspace = true }
rayon                    = { workspace = true }

serde                    = { workspace = true, optional = true }

[dev-dependencies]
cuprate-test-utils = { workspace = true }

tokio              = { workspace = true }
tempfile           = { workspace = true }
hex-literal        = { workspace = true }

[lints]
workspace = true
